name: to_do_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  #bloc
  flutter_bloc: ^9.1.1
  bloc: ^9.1.0
  hydrated_bloc: ^10.1.1
  equatable: ^2.0.8

  #storage
  path_provider: ^2.1.5
  shared_preferences: ^2.5.4

  #routing
  go_router: ^17.0.0

  #injection
  get_it: ^9.1.1
  dio: ^5.9.0
  cached_network_image: ^3.4.1
  data_connection_checker_tv: ^0.3.5-nullsafety

  #ui
  flutter_svg: ^2.2.3
  animations: ^2.1.1
  # glaze_nav_bar: ^1.2.1
  # curved_navigation_bar: ^1.0.6
  curved_labeled_navigation_bar: ^2.0.6
  #responsive
  flutter_screenutil: ^5.9.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  device_preview: ^1.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/poppines/
    - assets/icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppines/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppines/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppines/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppines/Poppins-Bold.ttf
          weight: 700
